FROM php:7.4-fpm

# Add PHP main config file
ADD ./custom.ini /usr/local/etc/php/conf.d/custom.ini

# Add PHP FPM Configurations
ADD ./www.conf /usr/local/etc/php-fpm.d/www.conf

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    vim

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install & configure PHP extensions
RUN docker-php-ext-install \
    bcmath \
    mysqli \
    pdo_mysql \
    pcntl \
    gd \
    && pecl install \
    mcrypt-1.0.2 \
    redis \
    && docker-php-ext-configure intl && docker-php-ext-install intl

# Enable PHP Extentions
RUN docker-php-ext-enable \
    mysqli \
    redis

# Add user for laravel application
RUN usermod -u 1000 www-data && \
    groupmod -g 1000 www-data

# Change current user to www
USER www-data

# Create Woring directory
RUN mkdir -p /var/www/html

# Set Worknig Directory
WORKDIR /var/www/html

# Expose port 9000 and start php-fpm server
EXPOSE 9000

# Dcoker command
CMD ["php-fpm"]